setup :
	echo "Configured for genbank release number [% conf.currentGBRelease %]"

[% conf.GB_TAXONOMY_DIR %]/[% conf.GB_TAXONOMY_ARC %] : 
	wget [% conf.GB_TAXONOMY_URL %] -O $@

[% conf.GB_TAXONOMY_DIR %]/names.dmp : [% conf.GB_TAXONOMY_DIR %]/[% conf.GB_TAXONOMY_ARC %]
	cd [% conf.GB_TAXONOMY_DIR %] && tar -zxvf [% conf.GB_TAXONOMY_ARC %] $(@F) && cd -

[% conf.GB_TAXONOMY_DIR %]/nodes.dmp : [% conf.GB_TAXONOMY_DIR %]/[% conf.GB_TAXONOMY_ARC %]
	cd [% conf.GB_TAXONOMY_DIR %] && tar -zxvf [% conf.GB_TAXONOMY_ARC %] $(@F) && cd -
	
taxonomy : [% conf.GB_TAXONOMY_DIR %]/names.dmp [% conf.GB_TAXONOMY_DIR %]/nodes.dmp

schema : [% conf.SCHEMA_FILE %]
	mysql -u [% conf.USER %] -p[% conf.PASS %] [% conf.DATABASE %] < $<

dao :
	perl -MDBIx::Class::Schema::Loader=make_schema_at,dump_to_dir:./lib \
		-e 'make_schema_at("Bio::Phylo::PhyLoTA::DAO", \
		{ db_schema => "phylota" }, \
		[ "dbi:[% conf.RDBMS %]:dbname=[% conf.DATABASE %]", "[% conf.USER %]", "[% conf.PASS %]" ])'

[% conf.DUMP_IN_FILE %] :
	curl [% conf.DUMP_IN_URL %][% conf.DUMP_IN_CHUNKS %] > $@

dldump : [% conf.DUMP_IN_FILE %]

load_dump : [% conf.DUMP_IN_FILE %]
	zcat $< | mysql -u [% conf.USER %] -p[% conf.PASS %] [% conf.DATABASE %]

[% conf.DUMP_OUT_FILE %].gz :
	mysqldump -u [% conf.USER %] -p[% conf.PASS %] [% conf.DATABASE %] | gzip -9 > $@

[% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_COMMONTREE %] : [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_SPECIESLIST %]
	perl -Ilib script/supersmart/write_common_tree.pl --nodelabels -i $< [% conf.SUPERSMART_VERBOSITY %] > $@

commontree : [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_COMMONTREE %]

[% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_ALIGNMENTLIST %] : [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_SPECIESLIST %]
	perl -Ilib script/supersmart/write_alignments.pl -i $< [% conf.SUPERSMART_VERBOSITY %] -s [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_ALIGNMENTSTEM %] > $@

alignments : [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_ALIGNMENTLIST %]

[% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_SUPERMATRIX %] : [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_ALIGNMENTLIST %]
	perl script/supersmart/concat_alignments.pl -l $< [% conf.SUPERSMART_VERBOSITY %] > $@

supermatrix : [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_SUPERMATRIX %]

[% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_RAXMLCON %] : [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_COMMONTREE %] [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_SUPERMATRIX %]
	perl script/supersmart/write_constraint_tree.pl -t [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_COMMONTREE %] -s [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_SUPERMATRIX %] [% conf.SUPERSMART_VERBOSITY %] > $@

constraint : [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_RAXMLCON %]

[% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_RAXML_RESULT %] : [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_RAXMLCON %] [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_SUPERMATRIX %]
	cd [% conf.SUPERSMART_WORKDIR %] && [% conf.SUPERSMART_RAXML %] [% conf.SUPERSMART_RAXML_ARGS %] -s [% conf.SUPERSMART_SUPERMATRIX %] -t [% conf.SUPERSMART_RAXMLCON %] -n [% conf.SUPERSMART_RAXML_RESULT %]

raxml : [% conf.SUPERSMART_WORKDIR %][% conf.SUPERSMART_RAXML_RESULT %]

[% conf.DOC_DIR %][% conf.DOC_OUT_FILE %] : [% conf.DOC_DIR %][% conf.DOC_IN_FILE %]
	cd [% conf.DOC_DIR %] && latex [% conf.DOC_IN_FILE %]

manuscript : [% conf.DOC_DIR %][% conf.DOC_OUT_FILE %]